/// Player animation action indices matching the C++ `_enum.h` PLAYER_* constants.
///
/// The enum is `#[repr(u16)]` with values 0..=286 (MAX_PLAYER_ACTION = 287 is the sentinel).
/// `AttackEnd` and `FlyRide` share value 74 (C++ alias); we keep only `FlyRide` in the enum
/// and provide `ATTACK_END_INDEX` for code that needs the raw value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum PlayerAction {
    Set = 0,
    StopMale = 1,
    StopFemale = 2,
    StopSummoner = 3,
    StopSword = 4,
    StopTwoHandSword = 5,
    StopSpear = 6,
    StopScythe = 7,
    StopBow = 8,
    StopCrossbow = 9,
    StopWand = 10,
    StopFly = 11,
    StopFlyCrossbow = 12,
    StopRide = 13,
    StopRideWeapon = 14,

    WalkMale = 15,
    WalkFemale = 16,
    WalkSword = 17,
    WalkTwoHandSword = 18,
    WalkSpear = 19,
    WalkScythe = 20,
    WalkBow = 21,
    WalkCrossbow = 22,
    WalkWand = 23,
    WalkSwim = 24,
    Run = 25,
    RunSword = 26,
    RunTwoSword = 27,
    RunTwoHandSword = 28,
    RunSpear = 29,
    RunBow = 30,
    RunCrossbow = 31,
    RunWand = 32,
    RunSwim = 33,
    Fly = 34,
    FlyCrossbow = 35,
    RunRide = 36,
    RunRideWeapon = 37,

    AttackFist = 38,
    AttackSwordRight1 = 39,
    AttackSwordRight2 = 40,
    AttackSwordLeft1 = 41,
    AttackSwordLeft2 = 42,
    AttackTwoHandSword1 = 43,
    AttackTwoHandSword2 = 44,
    AttackTwoHandSword3 = 45,
    AttackSpear1 = 46,
    AttackScythe1 = 47,
    AttackScythe2 = 48,
    AttackScythe3 = 49,
    AttackBow = 50,
    AttackCrossbow = 51,
    AttackFlyBow = 52,
    AttackFlyCrossbow = 53,
    AttackRideSword = 54,
    AttackRideTwoHandSword = 55,
    AttackRideSpear = 56,
    AttackRideScythe = 57,
    AttackRideBow = 58,
    AttackRideCrossbow = 59,

    AttackSkillSword1 = 60,
    AttackSkillSword2 = 61,
    AttackSkillSword3 = 62,
    AttackSkillSword4 = 63,
    AttackSkillSword5 = 64,
    AttackSkillWheel = 65,
    AttackSkillFuryStrike = 66,
    SkillVitality = 67,
    SkillRider = 68,
    SkillRiderFly = 69,
    AttackSkillSpear = 70,
    AttackOneToOne = 71,
    SkillHellBegin = 72,
    SkillHellStart = 73,

    // PLAYER_ATTACK_END = 74 aliased to FlyRide
    FlyRide = 74,
    FlyRideWeapon = 75,
    DarklordStand = 76,
    DarklordWalk = 77,
    StopRideHorse = 78,
    RunRideHorse = 79,
    AttackStrike = 80,
    AttackTeleport = 81,
    AttackRideStrike = 82,
    AttackRideTeleport = 83,
    AttackRideHorseSword = 84,
    AttackRideAttackFlash = 85,
    AttackRideAttackMagic = 86,
    AttackDarkhorse = 87,
    Idle1Darkhorse = 88,
    Idle2Darkhorse = 89,
    FenrirAttack = 90,
    FenrirAttackDarklordAqua = 91,
    FenrirAttackDarklordStrike = 92,
    FenrirAttackDarklordSword = 93,
    FenrirAttackDarklordTeleport = 94,
    FenrirAttackDarklordFlash = 95,
    FenrirAttackTwoSword = 96,
    FenrirAttackMagic = 97,
    FenrirAttackCrossbow = 98,
    FenrirAttackSpear = 99,
    FenrirAttackOneSword = 100,
    FenrirAttackBow = 101,
    FenrirSkill = 102,
    FenrirSkillTwoSword = 103,
    FenrirSkillOneRight = 104,
    FenrirSkillOneLeft = 105,
    FenrirDamage = 106,
    FenrirDamageTwoSword = 107,
    FenrirDamageOneRight = 108,
    FenrirDamageOneLeft = 109,
    FenrirRun = 110,
    FenrirRunTwoSword = 111,
    FenrirRunOneRight = 112,
    FenrirRunOneLeft = 113,
    FenrirRunMagom = 114,
    FenrirRunTwoSwordMagom = 115,
    FenrirRunOneRightMagom = 116,
    FenrirRunOneLeftMagom = 117,
    FenrirRunElf = 118,
    FenrirRunTwoSwordElf = 119,
    FenrirRunOneRightElf = 120,
    FenrirRunOneLeftElf = 121,
    FenrirStand = 122,
    FenrirStandTwoSword = 123,
    FenrirStandOneRight = 124,
    FenrirStandOneLeft = 125,
    FenrirWalk = 126,
    FenrirWalkTwoSword = 127,
    FenrirWalkOneRight = 128,
    FenrirWalkOneLeft = 129,

    AttackBowUp = 130,
    AttackCrossbowUp = 131,
    AttackFlyBowUp = 132,
    AttackFlyCrossbowUp = 133,
    AttackRideBowUp = 134,
    AttackRideCrossbowUp = 135,
    AttackOneFlash = 136,
    AttackRush = 137,
    AttackDeathCannon = 138,
    AttackRemoval = 139,
    AttackStun = 140,
    HighShock = 141,

    StopTwoHandSwordTwo = 142,
    WalkTwoHandSwordTwo = 143,
    RunTwoHandSwordTwo = 144,
    AttackTwoHandSwordTwo = 145,

    SkillHand1 = 146,
    SkillHand2 = 147,
    SkillWeapon1 = 148,
    SkillWeapon2 = 149,
    SkillElf1 = 150,
    SkillTeleport = 151,
    SkillFlash = 152,
    SkillInferno = 153,
    SkillHell = 154,
    RideSkill = 155,
    SkillSleep = 156,
    SkillSleepUni = 157,
    SkillSleepDino = 158,
    SkillSleepFenrir = 159,
    SkillChainLightning = 160,
    SkillChainLightningUni = 161,
    SkillChainLightningDino = 162,
    SkillChainLightningFenrir = 163,
    SkillLightningOrb = 164,
    SkillLightningOrbUni = 165,
    SkillLightningOrbDino = 166,
    SkillLightningOrbFenrir = 167,
    SkillDrainLife = 168,
    SkillDrainLifeUni = 169,
    SkillDrainLifeDino = 170,
    SkillDrainLifeFenrir = 171,
    SkillSummon = 172,
    SkillSummonUni = 173,
    SkillSummonDino = 174,
    SkillSummonFenrir = 175,
    SkillBlowOfDestruction = 176,
    SkillSwellOfMp = 177,
    SkillMultishotBowStand = 178,
    SkillMultishotBowFlying = 179,
    SkillMultishotCrossbowStand = 180,
    SkillMultishotCrossbowFlying = 181,
    SkillRecovery = 182,
    SkillGiganticstorm = 183,
    SkillFlamestrike = 184,
    SkillLightningShock = 185,

    // YDG_ADD_SKILL_RIDING_ANIMATIONS
    SkillGiganticstormUni = 186,
    SkillGiganticstormDino = 187,
    SkillGiganticstormFenrir = 188,
    AttackSkillWheelUni = 189,
    AttackSkillWheelDino = 190,
    AttackSkillWheelFenrir = 191,

    Defense1 = 192,
    Greeting1 = 193,
    GreetingFemale1 = 194,
    Goodbye1 = 195,
    GoodbyeFemale1 = 196,
    Clap1 = 197,
    ClapFemale1 = 198,
    Cheer1 = 199,
    CheerFemale1 = 200,
    Direction1 = 201,
    DirectionFemale1 = 202,
    Gesture1 = 203,
    GestureFemale1 = 204,
    Unknown1 = 205,
    UnknownFemale1 = 206,
    Cry1 = 207,
    CryFemale1 = 208,
    Awkward1 = 209,
    AwkwardFemale1 = 210,
    See1 = 211,
    SeeFemale1 = 212,
    Win1 = 213,
    WinFemale1 = 214,
    Smile1 = 215,
    SmileFemale1 = 216,
    Sleep1 = 217,
    SleepFemale1 = 218,
    Cold1 = 219,
    ColdFemale1 = 220,
    Again1 = 221,
    AgainFemale1 = 222,
    Respect1 = 223,
    Salute1 = 224,
    Scissors = 225,
    Rock = 226,
    Paper = 227,
    Hustle = 228,
    Provocation = 229,
    LookAround = 230,
    Cheers = 231,
    Rush1 = 232,
    ComeUp = 233,
    Shock = 234,
    Die1 = 235,
    Die2 = 236,
    Sit1 = 237,
    Sit2 = 238,
    SitFemale1 = 239,
    SitFemale2 = 240,
    Healing1 = 241,
    HealingFemale1 = 242,
    Pose1 = 243,
    PoseFemale1 = 244,
    Jack1 = 245,
    Jack2 = 246,
    Santa1 = 247,
    Santa2 = 248,
    ChangeUp = 249,
    RecoverSkill = 250,

    // PBG_ADD_NEWCHAR_MONK_SKILL
    SkillThrust = 251,
    SkillStamp = 252,
    SkillGiantswing = 253,
    SkillDarksideReady = 254,
    SkillDarksideAttack = 255,
    SkillDragonkick = 256,
    SkillDragonlore = 257,
    SkillAttUpOurforces = 258,
    SkillHpUpOurforces = 259,
    RageUniAttack = 260,
    RageUniAttackOneRight = 261,
    RageUniRun = 262,
    RageUniRunOneRight = 263,
    RageUniStopOneRight = 264,
    RageFenrir = 265,
    RageFenrirTwoSword = 266,
    RageFenrirOneRight = 267,
    RageFenrirOneLeft = 268,
    RageFenrirWalk = 269,
    RageFenrirWalkOneRight = 270,
    RageFenrirWalkOneLeft = 271,
    RageFenrirWalkTwoSword = 272,
    RageFenrirRun = 273,
    RageFenrirRunTwoSword = 274,
    RageFenrirRunOneRight = 275,
    RageFenrirRunOneLeft = 276,
    RageFenrirStand = 277,
    RageFenrirStandTwoSword = 278,
    RageFenrirStandOneRight = 279,
    RageFenrirStandOneLeft = 280,
    RageFenrirDamage = 281,
    RageFenrirDamageTwoSword = 282,
    RageFenrirDamageOneRight = 283,
    RageFenrirDamageOneLeft = 284,
    RageFenrirAttackRight = 285,
    StopRagefighter = 286,
}

/// Sentinel value (not a valid action).
pub const MAX_PLAYER_ACTION: u16 = 287;

/// Alias: PLAYER_ATTACK_END shares the same index as FlyRide.
pub const ATTACK_END_INDEX: u16 = 74;

impl PlayerAction {
    pub fn name(&self) -> &'static str {
        match self {
            Self::Set => "Set",
            Self::StopMale => "StopMale",
            Self::StopFemale => "StopFemale",
            Self::StopSummoner => "StopSummoner",
            Self::StopSword => "StopSword",
            Self::StopTwoHandSword => "StopTwoHandSword",
            Self::StopSpear => "StopSpear",
            Self::StopScythe => "StopScythe",
            Self::StopBow => "StopBow",
            Self::StopCrossbow => "StopCrossbow",
            Self::StopWand => "StopWand",
            Self::StopFly => "StopFly",
            Self::StopFlyCrossbow => "StopFlyCrossbow",
            Self::StopRide => "StopRide",
            Self::StopRideWeapon => "StopRideWeapon",
            Self::WalkMale => "WalkMale",
            Self::WalkFemale => "WalkFemale",
            Self::WalkSword => "WalkSword",
            Self::WalkTwoHandSword => "WalkTwoHandSword",
            Self::WalkSpear => "WalkSpear",
            Self::WalkScythe => "WalkScythe",
            Self::WalkBow => "WalkBow",
            Self::WalkCrossbow => "WalkCrossbow",
            Self::WalkWand => "WalkWand",
            Self::WalkSwim => "WalkSwim",
            Self::Run => "Run",
            Self::RunSword => "RunSword",
            Self::RunTwoSword => "RunTwoSword",
            Self::RunTwoHandSword => "RunTwoHandSword",
            Self::RunSpear => "RunSpear",
            Self::RunBow => "RunBow",
            Self::RunCrossbow => "RunCrossbow",
            Self::RunWand => "RunWand",
            Self::RunSwim => "RunSwim",
            Self::Fly => "Fly",
            Self::FlyCrossbow => "FlyCrossbow",
            Self::RunRide => "RunRide",
            Self::RunRideWeapon => "RunRideWeapon",
            Self::AttackFist => "AttackFist",
            Self::AttackSwordRight1 => "AttackSwordRight1",
            Self::AttackSwordRight2 => "AttackSwordRight2",
            Self::AttackSwordLeft1 => "AttackSwordLeft1",
            Self::AttackSwordLeft2 => "AttackSwordLeft2",
            Self::AttackTwoHandSword1 => "AttackTwoHandSword1",
            Self::AttackTwoHandSword2 => "AttackTwoHandSword2",
            Self::AttackTwoHandSword3 => "AttackTwoHandSword3",
            Self::AttackSpear1 => "AttackSpear1",
            Self::AttackScythe1 => "AttackScythe1",
            Self::AttackScythe2 => "AttackScythe2",
            Self::AttackScythe3 => "AttackScythe3",
            Self::AttackBow => "AttackBow",
            Self::AttackCrossbow => "AttackCrossbow",
            Self::AttackFlyBow => "AttackFlyBow",
            Self::AttackFlyCrossbow => "AttackFlyCrossbow",
            Self::AttackRideSword => "AttackRideSword",
            Self::AttackRideTwoHandSword => "AttackRideTwoHandSword",
            Self::AttackRideSpear => "AttackRideSpear",
            Self::AttackRideScythe => "AttackRideScythe",
            Self::AttackRideBow => "AttackRideBow",
            Self::AttackRideCrossbow => "AttackRideCrossbow",
            Self::AttackSkillSword1 => "AttackSkillSword1",
            Self::AttackSkillSword2 => "AttackSkillSword2",
            Self::AttackSkillSword3 => "AttackSkillSword3",
            Self::AttackSkillSword4 => "AttackSkillSword4",
            Self::AttackSkillSword5 => "AttackSkillSword5",
            Self::AttackSkillWheel => "AttackSkillWheel",
            Self::AttackSkillFuryStrike => "AttackSkillFuryStrike",
            Self::SkillVitality => "SkillVitality",
            Self::SkillRider => "SkillRider",
            Self::SkillRiderFly => "SkillRiderFly",
            Self::AttackSkillSpear => "AttackSkillSpear",
            Self::AttackOneToOne => "AttackOneToOne",
            Self::SkillHellBegin => "SkillHellBegin",
            Self::SkillHellStart => "SkillHellStart",
            Self::FlyRide => "FlyRide",
            Self::FlyRideWeapon => "FlyRideWeapon",
            Self::DarklordStand => "DarklordStand",
            Self::DarklordWalk => "DarklordWalk",
            Self::StopRideHorse => "StopRideHorse",
            Self::RunRideHorse => "RunRideHorse",
            Self::AttackStrike => "AttackStrike",
            Self::AttackTeleport => "AttackTeleport",
            Self::AttackRideStrike => "AttackRideStrike",
            Self::AttackRideTeleport => "AttackRideTeleport",
            Self::AttackRideHorseSword => "AttackRideHorseSword",
            Self::AttackRideAttackFlash => "AttackRideAttackFlash",
            Self::AttackRideAttackMagic => "AttackRideAttackMagic",
            Self::AttackDarkhorse => "AttackDarkhorse",
            Self::Idle1Darkhorse => "Idle1Darkhorse",
            Self::Idle2Darkhorse => "Idle2Darkhorse",
            Self::FenrirAttack => "FenrirAttack",
            Self::FenrirAttackDarklordAqua => "FenrirAttackDarklordAqua",
            Self::FenrirAttackDarklordStrike => "FenrirAttackDarklordStrike",
            Self::FenrirAttackDarklordSword => "FenrirAttackDarklordSword",
            Self::FenrirAttackDarklordTeleport => "FenrirAttackDarklordTeleport",
            Self::FenrirAttackDarklordFlash => "FenrirAttackDarklordFlash",
            Self::FenrirAttackTwoSword => "FenrirAttackTwoSword",
            Self::FenrirAttackMagic => "FenrirAttackMagic",
            Self::FenrirAttackCrossbow => "FenrirAttackCrossbow",
            Self::FenrirAttackSpear => "FenrirAttackSpear",
            Self::FenrirAttackOneSword => "FenrirAttackOneSword",
            Self::FenrirAttackBow => "FenrirAttackBow",
            Self::FenrirSkill => "FenrirSkill",
            Self::FenrirSkillTwoSword => "FenrirSkillTwoSword",
            Self::FenrirSkillOneRight => "FenrirSkillOneRight",
            Self::FenrirSkillOneLeft => "FenrirSkillOneLeft",
            Self::FenrirDamage => "FenrirDamage",
            Self::FenrirDamageTwoSword => "FenrirDamageTwoSword",
            Self::FenrirDamageOneRight => "FenrirDamageOneRight",
            Self::FenrirDamageOneLeft => "FenrirDamageOneLeft",
            Self::FenrirRun => "FenrirRun",
            Self::FenrirRunTwoSword => "FenrirRunTwoSword",
            Self::FenrirRunOneRight => "FenrirRunOneRight",
            Self::FenrirRunOneLeft => "FenrirRunOneLeft",
            Self::FenrirRunMagom => "FenrirRunMagom",
            Self::FenrirRunTwoSwordMagom => "FenrirRunTwoSwordMagom",
            Self::FenrirRunOneRightMagom => "FenrirRunOneRightMagom",
            Self::FenrirRunOneLeftMagom => "FenrirRunOneLeftMagom",
            Self::FenrirRunElf => "FenrirRunElf",
            Self::FenrirRunTwoSwordElf => "FenrirRunTwoSwordElf",
            Self::FenrirRunOneRightElf => "FenrirRunOneRightElf",
            Self::FenrirRunOneLeftElf => "FenrirRunOneLeftElf",
            Self::FenrirStand => "FenrirStand",
            Self::FenrirStandTwoSword => "FenrirStandTwoSword",
            Self::FenrirStandOneRight => "FenrirStandOneRight",
            Self::FenrirStandOneLeft => "FenrirStandOneLeft",
            Self::FenrirWalk => "FenrirWalk",
            Self::FenrirWalkTwoSword => "FenrirWalkTwoSword",
            Self::FenrirWalkOneRight => "FenrirWalkOneRight",
            Self::FenrirWalkOneLeft => "FenrirWalkOneLeft",
            Self::AttackBowUp => "AttackBowUp",
            Self::AttackCrossbowUp => "AttackCrossbowUp",
            Self::AttackFlyBowUp => "AttackFlyBowUp",
            Self::AttackFlyCrossbowUp => "AttackFlyCrossbowUp",
            Self::AttackRideBowUp => "AttackRideBowUp",
            Self::AttackRideCrossbowUp => "AttackRideCrossbowUp",
            Self::AttackOneFlash => "AttackOneFlash",
            Self::AttackRush => "AttackRush",
            Self::AttackDeathCannon => "AttackDeathCannon",
            Self::AttackRemoval => "AttackRemoval",
            Self::AttackStun => "AttackStun",
            Self::HighShock => "HighShock",
            Self::StopTwoHandSwordTwo => "StopTwoHandSwordTwo",
            Self::WalkTwoHandSwordTwo => "WalkTwoHandSwordTwo",
            Self::RunTwoHandSwordTwo => "RunTwoHandSwordTwo",
            Self::AttackTwoHandSwordTwo => "AttackTwoHandSwordTwo",
            Self::SkillHand1 => "SkillHand1",
            Self::SkillHand2 => "SkillHand2",
            Self::SkillWeapon1 => "SkillWeapon1",
            Self::SkillWeapon2 => "SkillWeapon2",
            Self::SkillElf1 => "SkillElf1",
            Self::SkillTeleport => "SkillTeleport",
            Self::SkillFlash => "SkillFlash",
            Self::SkillInferno => "SkillInferno",
            Self::SkillHell => "SkillHell",
            Self::RideSkill => "RideSkill",
            Self::SkillSleep => "SkillSleep",
            Self::SkillSleepUni => "SkillSleepUni",
            Self::SkillSleepDino => "SkillSleepDino",
            Self::SkillSleepFenrir => "SkillSleepFenrir",
            Self::SkillChainLightning => "SkillChainLightning",
            Self::SkillChainLightningUni => "SkillChainLightningUni",
            Self::SkillChainLightningDino => "SkillChainLightningDino",
            Self::SkillChainLightningFenrir => "SkillChainLightningFenrir",
            Self::SkillLightningOrb => "SkillLightningOrb",
            Self::SkillLightningOrbUni => "SkillLightningOrbUni",
            Self::SkillLightningOrbDino => "SkillLightningOrbDino",
            Self::SkillLightningOrbFenrir => "SkillLightningOrbFenrir",
            Self::SkillDrainLife => "SkillDrainLife",
            Self::SkillDrainLifeUni => "SkillDrainLifeUni",
            Self::SkillDrainLifeDino => "SkillDrainLifeDino",
            Self::SkillDrainLifeFenrir => "SkillDrainLifeFenrir",
            Self::SkillSummon => "SkillSummon",
            Self::SkillSummonUni => "SkillSummonUni",
            Self::SkillSummonDino => "SkillSummonDino",
            Self::SkillSummonFenrir => "SkillSummonFenrir",
            Self::SkillBlowOfDestruction => "SkillBlowOfDestruction",
            Self::SkillSwellOfMp => "SkillSwellOfMp",
            Self::SkillMultishotBowStand => "SkillMultishotBowStand",
            Self::SkillMultishotBowFlying => "SkillMultishotBowFlying",
            Self::SkillMultishotCrossbowStand => "SkillMultishotCrossbowStand",
            Self::SkillMultishotCrossbowFlying => "SkillMultishotCrossbowFlying",
            Self::SkillRecovery => "SkillRecovery",
            Self::SkillGiganticstorm => "SkillGiganticstorm",
            Self::SkillFlamestrike => "SkillFlamestrike",
            Self::SkillLightningShock => "SkillLightningShock",
            Self::SkillGiganticstormUni => "SkillGiganticstormUni",
            Self::SkillGiganticstormDino => "SkillGiganticstormDino",
            Self::SkillGiganticstormFenrir => "SkillGiganticstormFenrir",
            Self::AttackSkillWheelUni => "AttackSkillWheelUni",
            Self::AttackSkillWheelDino => "AttackSkillWheelDino",
            Self::AttackSkillWheelFenrir => "AttackSkillWheelFenrir",
            Self::Defense1 => "Defense1",
            Self::Greeting1 => "Greeting1",
            Self::GreetingFemale1 => "GreetingFemale1",
            Self::Goodbye1 => "Goodbye1",
            Self::GoodbyeFemale1 => "GoodbyeFemale1",
            Self::Clap1 => "Clap1",
            Self::ClapFemale1 => "ClapFemale1",
            Self::Cheer1 => "Cheer1",
            Self::CheerFemale1 => "CheerFemale1",
            Self::Direction1 => "Direction1",
            Self::DirectionFemale1 => "DirectionFemale1",
            Self::Gesture1 => "Gesture1",
            Self::GestureFemale1 => "GestureFemale1",
            Self::Unknown1 => "Unknown1",
            Self::UnknownFemale1 => "UnknownFemale1",
            Self::Cry1 => "Cry1",
            Self::CryFemale1 => "CryFemale1",
            Self::Awkward1 => "Awkward1",
            Self::AwkwardFemale1 => "AwkwardFemale1",
            Self::See1 => "See1",
            Self::SeeFemale1 => "SeeFemale1",
            Self::Win1 => "Win1",
            Self::WinFemale1 => "WinFemale1",
            Self::Smile1 => "Smile1",
            Self::SmileFemale1 => "SmileFemale1",
            Self::Sleep1 => "Sleep1",
            Self::SleepFemale1 => "SleepFemale1",
            Self::Cold1 => "Cold1",
            Self::ColdFemale1 => "ColdFemale1",
            Self::Again1 => "Again1",
            Self::AgainFemale1 => "AgainFemale1",
            Self::Respect1 => "Respect1",
            Self::Salute1 => "Salute1",
            Self::Scissors => "Scissors",
            Self::Rock => "Rock",
            Self::Paper => "Paper",
            Self::Hustle => "Hustle",
            Self::Provocation => "Provocation",
            Self::LookAround => "LookAround",
            Self::Cheers => "Cheers",
            Self::Rush1 => "Rush1",
            Self::ComeUp => "ComeUp",
            Self::Shock => "Shock",
            Self::Die1 => "Die1",
            Self::Die2 => "Die2",
            Self::Sit1 => "Sit1",
            Self::Sit2 => "Sit2",
            Self::SitFemale1 => "SitFemale1",
            Self::SitFemale2 => "SitFemale2",
            Self::Healing1 => "Healing1",
            Self::HealingFemale1 => "HealingFemale1",
            Self::Pose1 => "Pose1",
            Self::PoseFemale1 => "PoseFemale1",
            Self::Jack1 => "Jack1",
            Self::Jack2 => "Jack2",
            Self::Santa1 => "Santa1",
            Self::Santa2 => "Santa2",
            Self::ChangeUp => "ChangeUp",
            Self::RecoverSkill => "RecoverSkill",
            Self::SkillThrust => "SkillThrust",
            Self::SkillStamp => "SkillStamp",
            Self::SkillGiantswing => "SkillGiantswing",
            Self::SkillDarksideReady => "SkillDarksideReady",
            Self::SkillDarksideAttack => "SkillDarksideAttack",
            Self::SkillDragonkick => "SkillDragonkick",
            Self::SkillDragonlore => "SkillDragonlore",
            Self::SkillAttUpOurforces => "SkillAttUpOurforces",
            Self::SkillHpUpOurforces => "SkillHpUpOurforces",
            Self::RageUniAttack => "RageUniAttack",
            Self::RageUniAttackOneRight => "RageUniAttackOneRight",
            Self::RageUniRun => "RageUniRun",
            Self::RageUniRunOneRight => "RageUniRunOneRight",
            Self::RageUniStopOneRight => "RageUniStopOneRight",
            Self::RageFenrir => "RageFenrir",
            Self::RageFenrirTwoSword => "RageFenrirTwoSword",
            Self::RageFenrirOneRight => "RageFenrirOneRight",
            Self::RageFenrirOneLeft => "RageFenrirOneLeft",
            Self::RageFenrirWalk => "RageFenrirWalk",
            Self::RageFenrirWalkOneRight => "RageFenrirWalkOneRight",
            Self::RageFenrirWalkOneLeft => "RageFenrirWalkOneLeft",
            Self::RageFenrirWalkTwoSword => "RageFenrirWalkTwoSword",
            Self::RageFenrirRun => "RageFenrirRun",
            Self::RageFenrirRunTwoSword => "RageFenrirRunTwoSword",
            Self::RageFenrirRunOneRight => "RageFenrirRunOneRight",
            Self::RageFenrirRunOneLeft => "RageFenrirRunOneLeft",
            Self::RageFenrirStand => "RageFenrirStand",
            Self::RageFenrirStandTwoSword => "RageFenrirStandTwoSword",
            Self::RageFenrirStandOneRight => "RageFenrirStandOneRight",
            Self::RageFenrirStandOneLeft => "RageFenrirStandOneLeft",
            Self::RageFenrirDamage => "RageFenrirDamage",
            Self::RageFenrirDamageTwoSword => "RageFenrirDamageTwoSword",
            Self::RageFenrirDamageOneRight => "RageFenrirDamageOneRight",
            Self::RageFenrirDamageOneLeft => "RageFenrirDamageOneLeft",
            Self::RageFenrirAttackRight => "RageFenrirAttackRight",
            Self::StopRagefighter => "StopRagefighter",
        }
    }

    pub fn index(&self) -> usize {
        *self as usize
    }

    pub fn from_index(i: usize) -> Option<PlayerAction> {
        if i > 286 {
            return None;
        }
        // SAFETY: all values 0..=286 are valid discriminants in this repr(u16) enum.
        Some(unsafe { std::mem::transmute::<u16, PlayerAction>(i as u16) })
    }

    pub const ALL: &'static [PlayerAction] = &[
        Self::Set,
        Self::StopMale,
        Self::StopFemale,
        Self::StopSummoner,
        Self::StopSword,
        Self::StopTwoHandSword,
        Self::StopSpear,
        Self::StopScythe,
        Self::StopBow,
        Self::StopCrossbow,
        Self::StopWand,
        Self::StopFly,
        Self::StopFlyCrossbow,
        Self::StopRide,
        Self::StopRideWeapon,
        Self::WalkMale,
        Self::WalkFemale,
        Self::WalkSword,
        Self::WalkTwoHandSword,
        Self::WalkSpear,
        Self::WalkScythe,
        Self::WalkBow,
        Self::WalkCrossbow,
        Self::WalkWand,
        Self::WalkSwim,
        Self::Run,
        Self::RunSword,
        Self::RunTwoSword,
        Self::RunTwoHandSword,
        Self::RunSpear,
        Self::RunBow,
        Self::RunCrossbow,
        Self::RunWand,
        Self::RunSwim,
        Self::Fly,
        Self::FlyCrossbow,
        Self::RunRide,
        Self::RunRideWeapon,
        Self::AttackFist,
        Self::AttackSwordRight1,
        Self::AttackSwordRight2,
        Self::AttackSwordLeft1,
        Self::AttackSwordLeft2,
        Self::AttackTwoHandSword1,
        Self::AttackTwoHandSword2,
        Self::AttackTwoHandSword3,
        Self::AttackSpear1,
        Self::AttackScythe1,
        Self::AttackScythe2,
        Self::AttackScythe3,
        Self::AttackBow,
        Self::AttackCrossbow,
        Self::AttackFlyBow,
        Self::AttackFlyCrossbow,
        Self::AttackRideSword,
        Self::AttackRideTwoHandSword,
        Self::AttackRideSpear,
        Self::AttackRideScythe,
        Self::AttackRideBow,
        Self::AttackRideCrossbow,
        Self::AttackSkillSword1,
        Self::AttackSkillSword2,
        Self::AttackSkillSword3,
        Self::AttackSkillSword4,
        Self::AttackSkillSword5,
        Self::AttackSkillWheel,
        Self::AttackSkillFuryStrike,
        Self::SkillVitality,
        Self::SkillRider,
        Self::SkillRiderFly,
        Self::AttackSkillSpear,
        Self::AttackOneToOne,
        Self::SkillHellBegin,
        Self::SkillHellStart,
        Self::FlyRide,
        Self::FlyRideWeapon,
        Self::DarklordStand,
        Self::DarklordWalk,
        Self::StopRideHorse,
        Self::RunRideHorse,
        Self::AttackStrike,
        Self::AttackTeleport,
        Self::AttackRideStrike,
        Self::AttackRideTeleport,
        Self::AttackRideHorseSword,
        Self::AttackRideAttackFlash,
        Self::AttackRideAttackMagic,
        Self::AttackDarkhorse,
        Self::Idle1Darkhorse,
        Self::Idle2Darkhorse,
        Self::FenrirAttack,
        Self::FenrirAttackDarklordAqua,
        Self::FenrirAttackDarklordStrike,
        Self::FenrirAttackDarklordSword,
        Self::FenrirAttackDarklordTeleport,
        Self::FenrirAttackDarklordFlash,
        Self::FenrirAttackTwoSword,
        Self::FenrirAttackMagic,
        Self::FenrirAttackCrossbow,
        Self::FenrirAttackSpear,
        Self::FenrirAttackOneSword,
        Self::FenrirAttackBow,
        Self::FenrirSkill,
        Self::FenrirSkillTwoSword,
        Self::FenrirSkillOneRight,
        Self::FenrirSkillOneLeft,
        Self::FenrirDamage,
        Self::FenrirDamageTwoSword,
        Self::FenrirDamageOneRight,
        Self::FenrirDamageOneLeft,
        Self::FenrirRun,
        Self::FenrirRunTwoSword,
        Self::FenrirRunOneRight,
        Self::FenrirRunOneLeft,
        Self::FenrirRunMagom,
        Self::FenrirRunTwoSwordMagom,
        Self::FenrirRunOneRightMagom,
        Self::FenrirRunOneLeftMagom,
        Self::FenrirRunElf,
        Self::FenrirRunTwoSwordElf,
        Self::FenrirRunOneRightElf,
        Self::FenrirRunOneLeftElf,
        Self::FenrirStand,
        Self::FenrirStandTwoSword,
        Self::FenrirStandOneRight,
        Self::FenrirStandOneLeft,
        Self::FenrirWalk,
        Self::FenrirWalkTwoSword,
        Self::FenrirWalkOneRight,
        Self::FenrirWalkOneLeft,
        Self::AttackBowUp,
        Self::AttackCrossbowUp,
        Self::AttackFlyBowUp,
        Self::AttackFlyCrossbowUp,
        Self::AttackRideBowUp,
        Self::AttackRideCrossbowUp,
        Self::AttackOneFlash,
        Self::AttackRush,
        Self::AttackDeathCannon,
        Self::AttackRemoval,
        Self::AttackStun,
        Self::HighShock,
        Self::StopTwoHandSwordTwo,
        Self::WalkTwoHandSwordTwo,
        Self::RunTwoHandSwordTwo,
        Self::AttackTwoHandSwordTwo,
        Self::SkillHand1,
        Self::SkillHand2,
        Self::SkillWeapon1,
        Self::SkillWeapon2,
        Self::SkillElf1,
        Self::SkillTeleport,
        Self::SkillFlash,
        Self::SkillInferno,
        Self::SkillHell,
        Self::RideSkill,
        Self::SkillSleep,
        Self::SkillSleepUni,
        Self::SkillSleepDino,
        Self::SkillSleepFenrir,
        Self::SkillChainLightning,
        Self::SkillChainLightningUni,
        Self::SkillChainLightningDino,
        Self::SkillChainLightningFenrir,
        Self::SkillLightningOrb,
        Self::SkillLightningOrbUni,
        Self::SkillLightningOrbDino,
        Self::SkillLightningOrbFenrir,
        Self::SkillDrainLife,
        Self::SkillDrainLifeUni,
        Self::SkillDrainLifeDino,
        Self::SkillDrainLifeFenrir,
        Self::SkillSummon,
        Self::SkillSummonUni,
        Self::SkillSummonDino,
        Self::SkillSummonFenrir,
        Self::SkillBlowOfDestruction,
        Self::SkillSwellOfMp,
        Self::SkillMultishotBowStand,
        Self::SkillMultishotBowFlying,
        Self::SkillMultishotCrossbowStand,
        Self::SkillMultishotCrossbowFlying,
        Self::SkillRecovery,
        Self::SkillGiganticstorm,
        Self::SkillFlamestrike,
        Self::SkillLightningShock,
        Self::SkillGiganticstormUni,
        Self::SkillGiganticstormDino,
        Self::SkillGiganticstormFenrir,
        Self::AttackSkillWheelUni,
        Self::AttackSkillWheelDino,
        Self::AttackSkillWheelFenrir,
        Self::Defense1,
        Self::Greeting1,
        Self::GreetingFemale1,
        Self::Goodbye1,
        Self::GoodbyeFemale1,
        Self::Clap1,
        Self::ClapFemale1,
        Self::Cheer1,
        Self::CheerFemale1,
        Self::Direction1,
        Self::DirectionFemale1,
        Self::Gesture1,
        Self::GestureFemale1,
        Self::Unknown1,
        Self::UnknownFemale1,
        Self::Cry1,
        Self::CryFemale1,
        Self::Awkward1,
        Self::AwkwardFemale1,
        Self::See1,
        Self::SeeFemale1,
        Self::Win1,
        Self::WinFemale1,
        Self::Smile1,
        Self::SmileFemale1,
        Self::Sleep1,
        Self::SleepFemale1,
        Self::Cold1,
        Self::ColdFemale1,
        Self::Again1,
        Self::AgainFemale1,
        Self::Respect1,
        Self::Salute1,
        Self::Scissors,
        Self::Rock,
        Self::Paper,
        Self::Hustle,
        Self::Provocation,
        Self::LookAround,
        Self::Cheers,
        Self::Rush1,
        Self::ComeUp,
        Self::Shock,
        Self::Die1,
        Self::Die2,
        Self::Sit1,
        Self::Sit2,
        Self::SitFemale1,
        Self::SitFemale2,
        Self::Healing1,
        Self::HealingFemale1,
        Self::Pose1,
        Self::PoseFemale1,
        Self::Jack1,
        Self::Jack2,
        Self::Santa1,
        Self::Santa2,
        Self::ChangeUp,
        Self::RecoverSkill,
        Self::SkillThrust,
        Self::SkillStamp,
        Self::SkillGiantswing,
        Self::SkillDarksideReady,
        Self::SkillDarksideAttack,
        Self::SkillDragonkick,
        Self::SkillDragonlore,
        Self::SkillAttUpOurforces,
        Self::SkillHpUpOurforces,
        Self::RageUniAttack,
        Self::RageUniAttackOneRight,
        Self::RageUniRun,
        Self::RageUniRunOneRight,
        Self::RageUniStopOneRight,
        Self::RageFenrir,
        Self::RageFenrirTwoSword,
        Self::RageFenrirOneRight,
        Self::RageFenrirOneLeft,
        Self::RageFenrirWalk,
        Self::RageFenrirWalkOneRight,
        Self::RageFenrirWalkOneLeft,
        Self::RageFenrirWalkTwoSword,
        Self::RageFenrirRun,
        Self::RageFenrirRunTwoSword,
        Self::RageFenrirRunOneRight,
        Self::RageFenrirRunOneLeft,
        Self::RageFenrirStand,
        Self::RageFenrirStandTwoSword,
        Self::RageFenrirStandOneRight,
        Self::RageFenrirStandOneLeft,
        Self::RageFenrirDamage,
        Self::RageFenrirDamageTwoSword,
        Self::RageFenrirDamageOneRight,
        Self::RageFenrirDamageOneLeft,
        Self::RageFenrirAttackRight,
        Self::StopRagefighter,
    ];
}

/// Format an animation index as a display name.
/// Uses `PlayerAction` names for known indices, falls back to "Action{index}".
pub fn animation_display_name(index: usize) -> String {
    match PlayerAction::from_index(index) {
        Some(action) => format!("{:03} {}", index, action.name()),
        None => format!("{:03} Action{}", index, index),
    }
}
